[package]
name = "Realtime-chat-app"
version = "0.1.0"
edition = "2024"

[dependencies]
actix = "0.13.1"
actix-files = "0.6.2"
actix-web = "4.4.0"
actix-web-actors = "4.2.0"
actix-cors="0.5"
rand = "0.8.5"
serde = "1.0.188"
serde_json = "1.0.108"
diesel = { version = "1.4.8", features = ["r2d2"] }